### ISSUE TITLE
Urgent: Error 500 in Wordpress after installation/activation

### ISSUE THREAD

**Issue by andygellermann** [zgordon/gutenberg-course#17]
Hi Zac, thanks for your great course!
I need your support, I've tested your plugin in wordpress together with installed Gutenberg plugin.
It breaks down my Wordpress-Installation (4.9.4) with Servererror "500" and following response in Serverlog:

`6130#0: *591912 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to undefined function register_block_type() in /var/www/vhosts/gutenberg.example/wp-content/plugins/jsforwp-blocks/jsforwp-blocks.php:155
Stack trace:
#0 /var/www/vhosts/gutenberg.example/wp-settings.php(305): include_once()
#1 /var/www/vhosts/gutenberg.example/wp-config.php(78): require_once('/var/www/vhosts...')
#2 /var/www/vhosts/gutenberg.example/wp-load.php(37): require_once('/var/www/vhosts...')
#3 /var/www/vhosts/gutenberg.example/wp-admin/admin.php(31): require_once('/var/www/vhosts...')
#4 /var/www/vhosts/gutenberg.example/wp-admin/index.php(10): require_once('/var/www/vhosts...')
#5 {main}
thrown in /var/www/vhosts/gutenberg.example/wp-content/plugins/jsforwp-blocks/jsforwp-blocks.php on line 155" while reading response header from upstream`

Why they can't find the **register_block_type()**-Function delivered by Gutenberg-Plugin?
Is it the wrong way to use your code in Wordpress?

Thanks a lot for your quick support!
Best regards from berlin/germany
Andy

**Comment by andygellermann** [comment]
Okay, it's solved!
Sorry! Problem was (like existing other issues solving - at this point my mistake!) different names between plugin folder name and plugin php-filename!

Best from Berlin
Andy
